services:
  - type: web
    name: lookbook-backend
    env: python
    rootDir: backend
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput || echo "No static to collect"
      python manage.py migrate --noinput || echo "Migration step completed"
      # Ensure superuser (idempotent) if DJANGO_SUPERUSER_* envs are set
      python manage.py shell -c "import os; from django.contrib.auth import get_user_model; U=get_user_model(); u=os.getenv('DJANGO_SUPERUSER_USERNAME'); p=os.getenv('DJANGO_SUPERUSER_PASSWORD'); e=os.getenv('DJANGO_SUPERUSER_EMAIL','admin@example.com');
if u and p:
    obj, created = U.objects.get_or_create(username=u, defaults={'email': e});
    obj.is_active=True; obj.is_staff=True; obj.is_superuser=True; obj.set_password(p); obj.save();
    print('superuser ensured:', u, 'created=', created)
else:
    print('skip superuser creation: DJANGO_SUPERUSER_* not set')"
    startCommand: gunicorn lookbook.wsgi:application --bind 0.0.0.0:$PORT
    plan: free
    autoDeploy: true
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DJANGO_DEBUG
        value: "0"
      - key: DJANGO_ALLOWED_HOSTS
        value: .onrender.com
      - key: DJANGO_CORS_ALLOWED_ORIGINS
        value: https://<your-frontend>.onrender.com
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: https://lookbook-backend-qwfs.onrender.com
      - key: DJANGO_SUPERUSER_USERNAME
        sync: false
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false