# Generated by Django 5.2.7 on 2025-10-06 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('education', 'Education'), ('technology', 'Technology'), ('sports', 'Sports'), ('entertainment', 'Entertainment'), ('business', 'Business'), ('health', 'Health & Fitness'), ('travel', 'Travel'), ('food', 'Food & Cooking'), ('gaming', 'Gaming'), ('music', 'Music'), ('art', 'Art & Design'), ('other', 'Other')], default='general', max_length=50),
        ),
    ]
