# Generated by Django 5.2.7 on 2025-10-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='group_profiles/'),
        ),
    ]
