# Generated by Django 5.2.7 on 2025-10-04 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        ('posts', '0003_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='pages.page'),
        ),
    ]
