# Generated by Django 5.2.7 on 2025-10-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_use_rich_editor',
            field=models.BooleanField(default=False, help_text='Allow user to use rich text editor'),
        ),
        migrations.AddField(
            model_name='user',
            name='rich_editor_request_date',
            field=models.DateTimeField(blank=True, help_text='Date when user requested access', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rich_editor_requested',
            field=models.BooleanField(default=False, help_text='User has requested rich editor access'),
        ),
    ]
